services:
  queue-manager:
    hostname: queue-manager
    image: "ibmcom/mq"
    environment:
      LICENSE: accept
      MQ_QMGR_NAME: QM1
    ports:
      - "1414:1414"
      - "9443:9443"
  rest-mq-adapter:
    hostname: rest-mq-adapter
    image: rest-mq-adapter:1.0.0
    environment:
      QUEUE_MANAGER: QM1
      CHANNEL: DEV.ADMIN.SVRCONN
      CONNECTION_NAME: queue-manager(1414)
      RECEIVE_TIMEOUT: 5000
      MOCK_SOURCE_QUEUE: DEV.QUEUE.2
      MOCK_TARGET_QUEUE: DEV.QUEUE.3
      MOCK_RESPONSE_CCSID: 1208
      MOCK_RESPONSE_ENCODING: 273
      MOCK_RESPONSE_FILE: /opt/response.txt
      MOCK_RESPONSE_MESSAGE_TYPE: text
      LOG_LEVEL: INFO
    ports:
      - "8080:8080"
    volumes:
      - ./response.txt:/opt/response.txt
    depends_on:
      - queue-manager
